spring:
  application:
    name: discodeit
  profiles:
    active: dev   # 실행할 프로필 (dev / prod)

discodeit:
  storage:
    type: local
    local:
      root-path: /Users/apple/tmp/discodeit

logging:
  level:
    root: INFO

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'health, info, metrics, loggers'

info:
  app:
    name: ${spring.application.name}
    version: 1.7.0
  java:
    version: 17
  spring-boot:
    version: 3.4.2
  storage:
    type: ${discodeit.storage.type}
    path: ${discodeit.storage.local.root-path}