spring:
  application:
    name: discodeit
  profiles:
    active: dev   # 실행할 프로필 (dev / prod)

discodeit:
  storage:
    type: local
    local:
      root-path: /Users/apple/tmp/discodeit

logging:
  level:
    root: info
  file:
    name: logs/discodeit.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"